[tool.poetry]
name = "sitech-notifier"
version = "2.0.5"
description = "Notification library for real-time, sms and email notifications"
readme = 'README.md'
authors = ["Norbert Cyran <norbert@ulam.io>"]
classifiers=[
    'Programming Language :: Python :: 3',
    'Programming Language :: Python :: 3.6',
    'Programming Language :: Python :: 3.7',
    'Environment :: Web Environment',
    'Framework :: Django',
    'Operating System :: OS Independent',
]

[tool.poetry.dependencies]
python = "^3.6"
django = "^2.0 || ^3.0"
celery = "^4.3"
django-render-block = "^0.6.0"
pusher = {version = "^2.0", optional = true}

[tool.poetry.dev-dependencies]
pytest = "^3.0"
pytest-django = "^3.5"
flake8 = "^3.6"
pytest-cov = "^2.8"
pytest-pythonpath = "^0.7.3"
model_mommy = "^1.6"
pytest_mock = "^1.11"
tox = "^3.14"

[tool.poetry.extras]
realtime = ['pusher']

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
